package com.example.multi_tanent.sales.enums;

public enum SalesStatus {
    DRAFT,
    SENT,
    ACCEPTED,
    REJECTED,
    CANCELLED,
    ORDERED,
    RENTAL_ORDER,
    RENTAL_INVOICE,
    DELIVERED,
    RETURNED,
    SHIPPED,
    OPEN,
    PENDING,
    INVOICED,
    RENTAL_INVOICED,
    PROFORMA_INVOICED,
    CLOSED, CONVERTED,
    PARTIAL_RECEIVED,
    PARTIAL_RETURNED,
    FULLY_RETURNED,
    FULLY_RECEIVED;
}
